import eslintConfigPrettier from 'eslint-config-prettier';
import { defineConfig } from 'eslint/config';
import tseslint from 'typescript-eslint';
import narwhal from './index.js';

/*
Dogfood the published entry: one import for unicorn + sonarjs + conflict offs.
Prettier is repo-only (not part of shipped narwhal).
*/
export default defineConfig(
  {
    ignores: [
      'node_modules/**',
      // Generated by `npm run sync`
      'index.js',
      'conflicts.json',
    ],
  },
  ...narwhal,
  ...tseslint.configs.recommended,
  eslintConfigPrettier,
);
