import { defineConfig } from 'eslint/config';
import narwhal from './index.ts';

/*
Dogfood the published entry: options compose unicorn + sonarjs + typescript-eslint + prettier.
*/
export default defineConfig(
  {
    ignores: [
      'node_modules/**',
      'dist/**',
      // Generated by `npm run sync` / conflict snapshot
      'conflicts.json',
    ],
  },
  ...narwhal({
    typescript: true,
    typechecked: true,
    strict: true,
    stylistic: true,
    prettier: true,
  }),
  {
    languageOptions: {
      parserOptions: {
        projectService: {
          allowDefaultProject: ['*.js', 'eslint.config.js'],
        },
        tsconfigRootDir: import.meta.dirname,
      },
    },
  },
  {
    files: ['**/*.test.ts'],
    rules: {
      // node:test's describe/it commonly host async bodies without an await at the call site.
      '@typescript-eslint/no-floating-promises': 'off',
    },
  },
);
