/**
@generated by scripts/sync-narwhal.ts — do not hand-edit.
Unicorn rule offs that fight Sonar autofix intent.
*/
export const conflictOffs = {
  // Sonar-aligned prefer-number-properties wants Number.NaN; Unicorn autofix rewrites to NaN
  'unicorn/prefer-global-number-constants': 'off',
} as const satisfies import('eslint').Linter.RulesRecord;
