/**
@generated by scripts/sync-narwhal.ts — do not hand-edit.
Bundles unicorn + sonarjs recommended, then disables Unicorn rules that fight Sonar.
*/
import unicorn from 'eslint-plugin-unicorn';
import sonarjs from 'eslint-plugin-sonarjs';

export default [
	unicorn.configs.recommended,
	sonarjs.configs.recommended,
	{
		name: 'narwhal/sonar-over-unicorn',
		rules: {
			// Sonar-aligned prefer-number-properties wants Number.NaN; Unicorn autofix rewrites to NaN
			'unicorn/prefer-global-number-constants': 'off',
		},
	},
	{
		name: 'narwhal/eslint-config-entrypoint',
		files: ['**/eslint.config.{js,cjs,mjs,ts,cts,mts}'],
		rules: {
			// Flat config modules must evaluate top-level exports (defineConfig / arrays).
			'unicorn/no-top-level-side-effects': 'off',
		},
	},
];
