import { readFileSync, writeFileSync } from 'node:fs';
import { createRequire } from 'node:module';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import { detectConflicts, type ConflictMap } from './detect-conflicts.ts';

const require = createRequire(import.meta.url);
const root = path.join(path.dirname(fileURLToPath(import.meta.url)), '..');

const ESLINT_PEER = 'eslint';
const BUNDLED_DEPS = [
  '@eslint/js',
  'eslint-plugin-unicorn',
  'eslint-plugin-sonarjs',
  'typescript-eslint',
  'eslint-config-prettier',
] as const;

function renderGeneratedOffs(conflicts: ConflictMap): string {
  const ruleLines = Iterator.from(conflicts)
    .map(([ruleId, { why }]) => `\t// ${why}\n\t'${ruleId}': 'off',`)
    .toArray();

  return `/**
@generated by scripts/sync-narwhal.ts — do not hand-edit.
Unicorn rule offs that fight Sonar autofix intent.
*/
export const conflictOffs = {
${ruleLines.join('\n')}
} as const satisfies import('eslint').Linter.RulesRecord;
`;
}

function renderReadmeTable(conflicts: ConflictMap): string {
  const rows = Iterator.from(conflicts)
    .map(([ruleId, { why }]) => `| \`${ruleId}\` | ${why} |`)
    .toArray();
  return ['| Rule | Why Sonar wins |', '| --- | --- |', ...rows].join('\n');
}

function updateReadme(conflicts: ConflictMap): void {
  const readmePath = path.join(root, 'README.md');
  const readme = readFileSync(readmePath, 'utf8');
  const start = '<!-- narwhal:rules -->';
  const end = '<!-- /narwhal:rules -->';
  const block = `${start}\n${renderReadmeTable(conflicts)}\n${end}`;

  const startIndex = readme.indexOf(start);
  const endIndex = readme.indexOf(end);
  let next: string;
  if (startIndex === -1 || endIndex === -1) {
    const heading = '## What it disables\n\n';
    const headingIndex = readme.indexOf(heading);
    const duplicateMarker = '\n\nDuplicate Unicorn';
    const duplicateIndex = readme.indexOf(duplicateMarker, headingIndex);
    if (headingIndex === -1 || duplicateIndex === -1) {
      throw new Error('Could not find README rules section to update');
    }
    next =
      readme.slice(0, headingIndex + heading.length) +
      block +
      readme.slice(duplicateIndex);
  } else {
    next =
      readme.slice(0, startIndex) + block + readme.slice(endIndex + end.length);
  }

  writeFileSync(readmePath, next);
}

function installedVersion(packageName: string): string {
  const entry = require.resolve(packageName);
  let directory = path.dirname(entry);
  for (let index = 0; index < 6; index++) {
    try {
      const meta = JSON.parse(
        readFileSync(path.join(directory, 'package.json'), 'utf8'),
      ) as {
        name?: string;
        version?: string;
      };
      if (meta.name === packageName && meta.version) return meta.version;
    } catch {
      // keep walking
    }
    const parent = path.dirname(directory);
    if (parent === directory) break;
    directory = parent;
  }
  throw new Error(`Could not resolve version for ${packageName}`);
}

interface PackageJson {
  peerDependencies?: Record<string, string>;
  dependencies?: Record<string, string>;
  devDependencies?: Record<string, string>;
  scripts?: Record<string, string>;
  [key: string]: unknown;
}

function syncPackageJson(): void {
  const packagePath = path.join(root, 'package.json');
  const packageJson = JSON.parse(
    readFileSync(packagePath, 'utf8'),
  ) as PackageJson;
  packageJson.peerDependencies ??= {};
  packageJson.dependencies ??= {};
  packageJson.devDependencies ??= {};

  const eslintRange = `^${installedVersion(ESLINT_PEER)}`;
  packageJson.peerDependencies = { [ESLINT_PEER]: eslintRange };
  packageJson.devDependencies[ESLINT_PEER] = eslintRange;

  // Bundled so consumers only install this package (+ eslint).
  const nextPeers = { ...packageJson.peerDependencies };
  const nextDevelopment = { ...packageJson.devDependencies };
  for (const name of BUNDLED_DEPS) {
    packageJson.dependencies[name] = `^${installedVersion(name)}`;
    Reflect.deleteProperty(nextPeers, name);
    Reflect.deleteProperty(nextDevelopment, name);
  }
  packageJson.peerDependencies = nextPeers;
  packageJson.devDependencies = nextDevelopment;

  packageJson.scripts = {
    ...packageJson.scripts,
    build: 'tsc -p tsconfig.build.json',
    sync: 'tsx scripts/sync-narwhal.ts',
    test: 'tsx --test test/smoke.test.ts',
    typecheck: 'tsc -p tsconfig.json',
    lint: 'eslint .',
    'lint:fix': 'eslint . --fix',
    format: 'prettier --write .',
    'format:check': 'prettier --check .',
    prepare: 'husky || true',
    prepublishOnly: 'npm run build',
  };

  writeFileSync(packagePath, `${JSON.stringify(packageJson, undefined, 2)}\n`);
}

function writeConflictsJson(conflicts: ConflictMap): void {
  const payload = Object.fromEntries(conflicts);
  writeFileSync(
    path.join(root, 'conflicts.json'),
    `${JSON.stringify(payload, undefined, 2)}\n`,
  );
}

const conflicts = await detectConflicts();
writeFileSync(
  path.join(root, 'generated-offs.ts'),
  renderGeneratedOffs(conflicts),
);
writeConflictsJson(conflicts);
updateReadme(conflicts);
syncPackageJson();

console.log(`sync ok: ${String(conflicts.size)} unicorn rule(s) disabled`);
for (const [ruleId, { why }] of conflicts) {
  console.log(`  - ${ruleId}: ${why}`);
}
