import { readFileSync, writeFileSync } from 'node:fs';
import { createRequire } from 'node:module';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import { detectConflicts, type ConflictMap } from './detect-conflicts.ts';

const require = createRequire(import.meta.url);
const root = path.join(path.dirname(fileURLToPath(import.meta.url)), '..');

const ESLINT_PEER = 'eslint';
const BUNDLED_PLUGINS = [
  'eslint-plugin-unicorn',
  'eslint-plugin-sonarjs',
] as const;

function renderIndex(conflicts: ConflictMap): string {
  const ruleLines = Iterator.from(conflicts)
    .map(([ruleId, { why }]) => `\t\t\t// ${why}\n\t\t\t'${ruleId}': 'off',`)
    .toArray();

  return `/**
@generated by scripts/sync-narwhal.ts — do not hand-edit.
Bundles unicorn + sonarjs recommended, then disables Unicorn rules that fight Sonar.
*/
import unicorn from 'eslint-plugin-unicorn';
import sonarjs from 'eslint-plugin-sonarjs';

export default [
	unicorn.configs.recommended,
	sonarjs.configs.recommended,
	{
		name: 'narwhal/sonar-over-unicorn',
		rules: {
${ruleLines.join('\n')}
		},
	},
	{
		name: 'narwhal/eslint-config-entrypoint',
		files: ['**/eslint.config.{js,cjs,mjs,ts,cts,mts}'],
		rules: {
			// Flat config modules must evaluate top-level exports (defineConfig / arrays).
			'unicorn/no-top-level-side-effects': 'off',
		},
	},
];
`;
}

function renderReadmeTable(conflicts: ConflictMap): string {
  const rows = Iterator.from(conflicts)
    .map(([ruleId, { why }]) => `| \`${ruleId}\` | ${why} |`)
    .toArray();
  return ['| Rule | Why Sonar wins |', '| --- | --- |', ...rows].join('\n');
}

function updateReadme(conflicts: ConflictMap): void {
  const readmePath = path.join(root, 'README.md');
  const readme = readFileSync(readmePath, 'utf8');
  const start = '<!-- narwhal:rules -->';
  const end = '<!-- /narwhal:rules -->';
  const block = `${start}\n${renderReadmeTable(conflicts)}\n${end}`;

  const startIndex = readme.indexOf(start);
  const endIndex = readme.indexOf(end);
  let next: string;
  if (startIndex === -1 || endIndex === -1) {
    const heading = '## What it disables\n\n';
    const headingIndex = readme.indexOf(heading);
    const duplicateMarker = '\n\nDuplicate Unicorn';
    const duplicateIndex = readme.indexOf(duplicateMarker, headingIndex);
    if (headingIndex === -1 || duplicateIndex === -1) {
      throw new Error('Could not find README rules section to update');
    }
    next =
      readme.slice(0, headingIndex + heading.length) +
      block +
      readme.slice(duplicateIndex);
  } else {
    next =
      readme.slice(0, startIndex) + block + readme.slice(endIndex + end.length);
  }

  writeFileSync(readmePath, next);
}

function installedVersion(packageName: string): string {
  const entry = require.resolve(packageName);
  let directory = path.dirname(entry);
  for (let index = 0; index < 6; index++) {
    try {
      const meta = JSON.parse(
        readFileSync(path.join(directory, 'package.json'), 'utf8'),
      ) as {
        name?: string;
        version?: string;
      };
      if (meta.name === packageName && meta.version) return meta.version;
    } catch {
      // keep walking
    }
    const parent = path.dirname(directory);
    if (parent === directory) break;
    directory = parent;
  }
  throw new Error(`Could not resolve version for ${packageName}`);
}

type PackageJson = {
  peerDependencies?: Record<string, string>;
  dependencies?: Record<string, string>;
  devDependencies?: Record<string, string>;
  scripts?: Record<string, string>;
  [key: string]: unknown;
};

function syncPackageJson(): void {
  const packagePath = path.join(root, 'package.json');
  const packageJson = JSON.parse(
    readFileSync(packagePath, 'utf8'),
  ) as PackageJson;
  packageJson.peerDependencies ??= {};
  packageJson.dependencies ??= {};
  packageJson.devDependencies ??= {};

  const eslintRange = `^${installedVersion(ESLINT_PEER)}`;
  packageJson.peerDependencies = { [ESLINT_PEER]: eslintRange };
  packageJson.devDependencies[ESLINT_PEER] = eslintRange;

  // Plugins ship with narwhal so consumers only install this package (+ eslint).
  for (const name of BUNDLED_PLUGINS) {
    const range = `^${installedVersion(name)}`;
    packageJson.dependencies[name] = range;
    delete packageJson.peerDependencies[name];
    delete packageJson.devDependencies[name];
  }

  packageJson.scripts = {
    ...packageJson.scripts,
    sync: 'tsx scripts/sync-narwhal.ts',
    test: 'tsx --test test/smoke.test.ts',
    typecheck: 'tsc -p tsconfig.json',
    lint: 'eslint .',
    'lint:fix': 'eslint . --fix',
    format: 'prettier --write .',
    'format:check': 'prettier --check .',
    prepare: 'husky',
  };

  writeFileSync(packagePath, `${JSON.stringify(packageJson, undefined, 2)}\n`);
}

function writeConflictsJson(conflicts: ConflictMap): void {
  const payload = Object.fromEntries(conflicts);
  writeFileSync(
    path.join(root, 'conflicts.json'),
    `${JSON.stringify(payload, undefined, 2)}\n`,
  );
}

const conflicts = await detectConflicts();
writeFileSync(path.join(root, 'index.js'), renderIndex(conflicts));
writeConflictsJson(conflicts);
updateReadme(conflicts);
syncPackageJson();

console.log(`sync ok: ${conflicts.size} unicorn rule(s) disabled`);
for (const [ruleId, { why }] of conflicts) {
  console.log(`  - ${ruleId}: ${why}`);
}
